# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================
logging:
  level:
    ROOT: WARN
    pbs.api: DEBUG
    pbs.api.mappers:
      AuthMapper: INFO
    pbs.api.domain.diaries.DiaryDao.selectUser: INFO

datasources:
  database:
    username: admin
    password: admin
    port: 5444
    schema: diary
    host: localhost

spring:
  profiles:
    include:
      - swagger
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
  flyway:
    locations: "classpath:/db/migration, classpath:/db/test"

storage:
  location: "./dev/files/"
