insert into operations(operation_name, operation_priority) values ('Wypłata z bankomatu', 1);
insert into operations(operation_name, operation_priority) values ('Płatność kartą - zbliżeniowo', 2);
insert into operations(operation_name, operation_priority) values ('Płatność kartą - tradycyjnie', 3);
insert into operations(operation_name, operation_priority) values ('Płatność zbliżeniowa telefonem', 4);
insert into operations(operation_name, operation_priority) values ('Płatność iPKO', 5);
insert into operations(operation_name, operation_priority) values ('Przelew krajowy', 6);
insert into operations(operation_name, operation_priority) values ('Przelew zagraniczny', 7);
insert into operations(operation_name, operation_priority) values ('Płatność BLIK', 8);
insert into operations(operation_name, operation_priority) values ('Wizyta w agencji/ oddziale', 9);
insert into operations(operation_name, operation_priority) values ('Korzystanie z aplikacji mobilnej IKO', 10);
insert into operations(operation_name, operation_priority) values ('Logowanie na stronie PKO BP', 11);
insert into operations(operation_name, operation_priority) values ('Infolinia', 12);
insert into operations(operation_name, operation_priority) values ('Inne (jakie?)', 13);
insert into operations(operation_name, operation_priority) values ('Brak aktywności', 14);
